general {
    # Mengunci layar sebelum suspend (opsional, tapi disarankan keamanan)
    # before_sleep_cmd = loginctl lock-session
    
    # Menyalakan layar kembali jika ada input
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 800
    on-timeout = hyprlock
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800
    on-timeout = sh -c 'grep -q 0 /sys/class/power_supply/AC/online && systemctl suspend'
}

listener {
    timeout = 2700
    on-timeout = systemctl suspend
}
