#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar & hypridle
exec-once = swayosd-server
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = nm-applet --indicator
exec-once = swww-daemon & systemctl --user start wallpaper-swww-timer.service & ~/.config/my-plugins/auto-pause.sh
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard regular
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
