##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = search_lancher
    #match:initial_class = ^(Search*Launcher)$
    match:class = search_launcher
    #match:initial_title = ^(_/home/rogan/.config/my-plugins/search.html)$
    # match:title=search.html
    float = true
    size = 600 600
    center = true
    no_shadow = on
    no_blur = on
    pin = on
    stay_focused = on
    border_size = 0
}

windowrule {
    name = btop-open
    match:class = btop_float
    float = on

    size = 800 650
}

windowrule {
    name = bandwhich-open
    match:class = bandwhich_float
    float = on

    size = 800 650
}

windowrule {
    name = pavu-control-float
    match:class = org.pulseaudio.pavucontrol
    match:title = Volume Control

    center = true
    size = 800 600
    float = on
}

windowrule {
    name = blueman-float
    match:class = blueman-manager
    match:title = Bluetooth Devices

    center = true
    float = on
}

windowrule {
    name = network-float
    match:class = nm-connection-editor
    match:title = Network Connections

    center = true
    float = on
}

windowrule {
    name = sticky-notes
    #match:initial_title = ^(Sticky Note)$
    match:class = com.vixalien.sticky 
    float = true
    pin = true
    size = 100 100
    move = 140 100
}

windowrule {
    name = ask-file
    match:class = ^(code)$
    match:title = ^(Open Folder|Open [Ff]iles?|Save|Save [Aa]s)$
    float = true
}
